apiVersion: v1
kind: Service
metadata:
  name: k8s-external-post-mysql-service
spec:
  ports:
    - port: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: k8s-external-post-mysql-service
subsets:
  - addresses:
      - ip: 115.137.9.160
    ports:
      - port: 13307
